apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
data:
  telegraf.conf: |
    [global_tags]

    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      hostname = ""
      omit_hostname = false

    [[outputs.influxdb_v2]]
      urls = ["http://influxdb:8086"]
      token = "${INFLUXDB_ADMIN_TOKEN}"
      organization = "${INFLUXDB_ORG}"
      bucket = "${INFLUXDB_BUCKET}"

    [[inputs.mqtt_consumer]]
      servers = ["tcp://mqtt-broker:1883"]
      topics = [
        "sensors/#"
      ]
      data_format = "json"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: telegraf
        volumeMounts:
        - name: telegraf-config
          mountPath: /etc/telegraf/telegraf.conf
          subPath: telegraf.conf
      volumes:
      - name: telegraf-config
        configMap:
          name: telegraf-config 